- src/auditlog/models.py
django-polymorphic self._get_pk_value returns the class object.  If
this happens, we try adding _id to the pk_field.
> - Compatibility with django-polymorphic

- src/auditlog/models.py
- src/auditlog_tests/models.py
- src/auditlog_tests/tests.py
> Helper method for many to many relationships

- docs/source/usage.rst
- src/auditlog/middleware.py
- src/auditlog/migrations/0003_logentry_remote_addr.py
- src/auditlog/models.py
- src/auditlog_tests/test_settings.py
Own version of functionality from #20, closes #27.
> Use threadlocals and log remote address

- .travis.yml
- src/auditlog/diff.py
Fixes:
- Compare objects instead of string representations (as suggested in #25)
- Compare values against the field's default value instead of ```None``` (as suggested in #26)
- Use the new _meta API to get the fields
> Improve diffs

- src/auditlog/middleware.py
> Fixes #31 with threadlocal

- .travis.yml
- src/auditlog/__init__.py
- src/auditlog/apps.py
- src/auditlog_tests/__init__.py
- src/auditlog_tests/apps.py
Includes fixes for:
- Issue #33 (App loading)
> Django 1.9 support

- requirements.txt
- src/auditlog/models.py
> Upgrade django-jsonfield dependency

- src/auditlog/migrations/0006_object_pk_index.py
> Change existing migration to fix issues for MySQL users

- src/auditlog/admin.py
> added a simple admin interface for audit log entries

- src/auditlog/middleware.py
> Update middleware for Django 1.10

- .gitignore
- setup.py
- src/auditlog/admin.py
- src/auditlog/filters.py
- src/auditlog/mixins.py
Please review and let me know if you prefer this admin interface over the initial simple one for issue #55
> enhanced admin interface

- src/auditlog/admin.py
- src/auditlog/mixins.py
Hey,
This is partly a duplicate of PR #80, but this fixes another issue in the admin where the search field doesn't work in the Auditlog admin. Fixes #83 and replaces PR #80. You might want to choose to only cherry-pick the second commit though if you want to merge the other PR.
> Django Admin full_name fix

- .gitignore
- .travis.yml
- requirements-test.txt
- requirements.txt
- tox.ini
PR brings an updated testing model utilizing tox to quickly run tests against different all compatible python versions for each [currently supported version of Django](https://www.djangoproject.com/download/#supported-versions). Also starts tracking code coverage for our tests by using the coverage package and integrating with the free for open source codecov website.
> Chore -- Update testing

- .travis.yml
- requirements-test.txt
When this is merged, Travis CI can deploy a new version to PyPI.
How to release:
1. Make sure all tests on `master` are green.
2. Create a new branch `vX.Y.Z` from master for that specific release.
3. Bump versions in `setup.py` and `docs/source/conf.py` (docs have 2 places where the versions need to be changed!)
4. Pull request `vX.Y.Z` -> `stable`. Merging policy is very strict. This triggers a new release.
5. Pull request `stable` -> `master`. Now everything is back in sync.
Opening a pull request from `master` directly to `stable` is discouraged as `master` may be updated while the PR is open, thus changing the contents of the release.
Sadly, this cannot be tested until the first release is done this way. At the moment `master` is not stable, so no `stable` branch has been created.
> Add deploy config for Travis CI

- .travis.yml
This should hopefully get the release to pypi working!
> Fix TOXENV variable name in deploy step

- .travis.yml
Fix TOXENV variable name in deploy step (#217)
> Fix package deploy

- .travis.yml
> Kick off the build

- .travis.yml
- CONTRIBUTING.md
- README.md
- docs/source/index.rst
- docs/source/installation.rst
- setup.py
See issue #268 for details and a task list.
> Changes for Jazzband

- auditlog/mixins.py
This will add content type name to resource_url field.
> Add content type to resource field

- auditlog/models.py
Continue to https://github.com/jazzband/django-auditlog/pull/335
I've just rebased the patch.
> replace ugettext with gettext for django4

- auditlog/apps.py
After https://github.com/jazzband/django-auditlog/commit/ffd8bb1e85fe7ed80d85062e4d5932f28065b84c we have [black error](https://github.com/jazzband/django-auditlog/runs/4773356797?check_suite_focus=true)
> Fix black error.

- README.md
- setup.py
Those URLs can be useful:
- the doc link
- the source link
- the tracker link.
> build(setup): add some project URLs

- docs/source/usage.rst
Fix small typo
`AuditLogHistoryField` -> `AuditlogHistoryField`
> Fix small typo

- CHANGELOG.md
- auditlog/__init__.py
- auditlog_tests/__init__.py
Fixes https://github.com/jazzband/django-auditlog/issues/366
> Remove `default_app_config` configuration

- auditlog_tests/models.py
- auditlog_tests/tests.py
See https://github.com/jjkester/django-auditlog/issues/17
> tests:  Check cases when reverse related field DoesNotExist.

- CHANGELOG.md
Closes https://github.com/jazzband/django-auditlog/issues/389
> Prepare release 2.1.0

- CHANGELOG.md
- auditlog/mixins.py
- auditlog_tests/tests.py
> Display changes for deleted objects in the admin

- docs/source/usage.rst
> Fix code block in usage.rst

- README.md
Need the project lead validation, to be sure ;).
> docs(readme): update the release section

- CHANGELOG.md
- auditlog/admin.py
> Support search by custom USERNAME_FIELD

- CHANGELOG.md
Fix https://github.com/jazzband/django-auditlog/issues/418
> Prepare release 2.2.0

- docs/make.bat
resolve https://github.com/jazzband/django-auditlog/issues/463
> update docs folder link

- auditlog/admin.py
- auditlog/apps.py
- auditlog/filters.py
- auditlog/mixins.py
Some parts were already implemented with gettext_lazy but the rest were  missed.
I've added gettext_lazy to other parts of project like mixins and filters too because it's a very important option for a multilingual website.
> Complete translation with gettext_lazy

- CHANGELOG.md
Bugfix release based on https://github.com/jazzband/django-auditlog/issues/493#issuecomment-1384087835
> Prepare release 2.2.2

- auditlog/models.py
- auditlog_tests/tests.py
See #513 for an explanation of the issue at hand!
> Make M2M changes comply with JSONField properly

- .pre-commit-config.yaml
- CHANGELOG.md
- auditlog/migrations/0001_initial.py
- auditlog/migrations/0002_auto_support_long_primary_keys.py
- auditlog/migrations/0003_logentry_remote_addr.py
- auditlog/migrations/0004_logentry_detailed_object_repr.py
- auditlog/migrations/0005_logentry_additional_data_verbose_name.py
- auditlog/migrations/0006_object_pk_index.py
- auditlog/migrations/0007_object_pk_type.py
- auditlog/migrations/0008_action_index.py
- auditlog/migrations/0009_alter_logentry_additional_data.py
- auditlog/migrations/0010_alter_logentry_timestamp.py
- auditlog/migrations/0011_logentry_serialized_data.py
- auditlog/migrations/0012_add_logentry_action_access.py
- auditlog/mixins.py
- auditlog/receivers.py
- auditlog_tests/tests.py
- setup.py
- tox.ini
Backport https://github.com/jazzband/django-auditlog/commit/fcb6c4ce2716ff780c020ebce0b4cc6f3c103e65
> [Backport] Fix a bug in audit log admin page when USE_TZ=False

- auditlog/management/commands/auditlogmigratejson.py
- auditlog_tests/test_two_step_json_migration.py
I also fixed a type and improved the styling of the command output.
> chore: add a check arg to the migration command

- .github/workflows/test.yml
Django [dropped support for Postgres 12](https://github.com/django/django/commit/2c6ebb65c9eb6b11347d907127b82d31e04569e5)
> Update postgres to 13

- CHANGELOG.md
- auditlog/context.py
- auditlog/receivers.py
replace threading.local() with contextvars to be able to use with Django 4.2
> use contextvar instead of threadlocal

- CHANGELOG.md
- auditlog/diff.py
- auditlog_tests/tests.py
Fixes https://github.com/jazzband/django-auditlog/issues/577
> Fixed problem when setting `django.db.models.functions.Now()` in `DateTimeField`

- CHANGELOG.md
- auditlog/conf.py
- auditlog/registry.py
- auditlog_tests/tests.py
- docs/source/usage.rst
Fixes https://github.com/jazzband/django-auditlog/issues/701
> Add ability to globally mask fields by name on all models.

- auditlog/context.py
> improve actor_email assignment

- auditlog/diff.py
- auditlog_tests/test_app/models.py
- auditlog_tests/tests.py
related: https://github.com/jazzband/django-auditlog/pull/725#issuecomment-2943030068
> Fix `get_field_value` field default value handling for Django 6.0 compatibility
