jazzband/django-auditlog

- src/auditlog/middleware.py
- src/auditlog/models.py
to remove the following Django Warning:
> site-packages/auditlog/models.py:6: RemovedInDjango19Warning:
> django.contrib.contenttypes.generic is deprecated and will be removed in Django 1.9. Its contents have been moved to the fields, forms, and admin submodules of django.contrib.contenttypes.
> from django.contrib.contenttypes import generic
> Changed import statement and reference to GenericRelation in order

- src/auditlog/migrations/0005_logentry_additional_data_verbose_name.py
- src/auditlog/migrations/0006_object_pk_index.py
- src/auditlog/models.py
Was seeing a big hit on heroku because of object_pk not having an index. This seems to clean it up. The 0005 migration is happening automatically when I run makemigrations and doesnt really change anything.
> Add db_index to object_pk

- src/auditlog/models.py
When using LogEntry.get_for_objects with a model that has an automatic (numeric) primary key, the following error occurs:
```
operator does not exist: text = integer LINE 1: ...ction_id" = 1) OR "auditlog_logentry"."object_pk" IN (SELECT... ^ HINT: No operator matches the given name and argument type(s). You might need to add explicit type casts.
```
I suspect this is a Postgres-specific error.
> Change LogEntry.get_for_objects to distinguish between number and text keys.

- src/auditlog/diff.py
- src/auditlog_tests/models.py
- src/auditlog_tests/test_settings.py
- src/auditlog_tests/tests.py
Django converts the timezone of DateTimeFields to UTC when the field gets saved, when you update a model which includes a DateTimeField, and your server is running in another timezone. This results in the AuditLog thinking you changed the timestamp, while it actually is the same time, but in another timezone.
This PR adds a specific check in the model_instance_diff function for DateTimeField models (and any subclasses of it), which converts the old and new values to UTC before comparing them to see if they've actually changed. It also adds tests to see if the code works properly. This fixes #82.
The extra test_setting (USE_TZ) is added because timezone support is disabled if it is not specified, this setting enables it.
DateFields are not timezone-aware, so they do not need fixing.
> Properly check timezone-aware DateTimeFields for changes

- src/auditlog/management/commands/auditlogflush.py
NoArgsCommand was removed in Django 1.10. Switched to BaseCommand which defaults to no arguments. This fixes the management command autologflush in Django 1.10
> Fixed autologflush for django 1.10

- src/auditlog/diff.py
My Django app is using the setting USE_TZ=False and it is throwing the following error:
If I change the settings to True, it work like a charm (but I cant change it by now). We need to support applications that use this settings to False.
So, I added a verification to consider the timezone only if it is enable in the Django app.
> Use make_naive only if settings.USE_TZ is True.

- src/auditlog/registry.py
- src/auditlog_tests/models.py
This allows this usage:
~~~
@auditlog.register(exclude_fields=["foo", "bar"])
class SimpleModel(models.Model):
~~~
> Allow register() to be called as a decorator (closes #88)

- src/auditlog/diff.py
> Deprecate the use of field.rel except for django 1.8

- src/auditlog/models.py
- src/auditlog_tests/models.py
- src/auditlog_tests/tests.py
This PR adds support for models with primary keys that use Django's UUIDField.
Fixes #110
> Support models with UUID primary keys

- setup.py
We weren't actually packaging up the management command when we published to PyPI, fixes #129
> Add management commands package to setup.py

- MANIFEST
- src/auditlog/compat.py
- src/auditlog/middleware.py
- src/auditlog/migrations/0001_initial.py
- src/auditlog/mixins.py
- src/auditlog/models.py
- src/auditlog_tests/models.py
- src/auditlog_tests/test_settings.py
- src/auditlog_tests/tests.py
- tox.ini
Changes as noted in #153 for compatibility with django v2.0. All tox tests I can run are passing (but `py27-django-111` is refusing to run for me due to a dependancy problem as `functools` apparently doesn't like me today ...)
Still have to add in the migrations — let me know if you want them sequential or squashed.
> Changes Required for Compatibility with Django 2.0

- src/auditlog/models.py
- src/auditlog_tests/tests.py
Found some bugs with my previous pr to add `changes_display_dict` property.
This PR Fixes four bugs discovered with changes_display_dict, three that caused crashes and the other was datetimes being displayed in UTC instead of the servers set timezone.
> (bugfix) changes_display_dict errors

- src/auditlog/mixins.py
When I used Django-auditlog with Django==2.0.1, field "msg" was not rendered as HTML. Instead, it was showing as plain text. So I used "mark_safe" where the HTML was generated, which fixed the issue.
> Corrected the issue when audit log when using django Django==2.0.1

- src/auditlog/mixins.py
As per my comment (https://github.com/jjkester/django-auditlog/pull/159#issuecomment-361938038). I believe using [`format_html`](https://docs.djangoproject.com/en/2.0/ref/utils/#django.utils.html.format_html) to be a better solution to that proposed in #159.
* Remove `allow_tags` as they've been deprecated as of Django 2.0
* Use `format_html` to provide conditional escaping and `mark_safe` functionality
> Mark LogEntryAdminMixin methods output as safe where required

- src/auditlog/models.py
- src/auditlog_tests/models.py
- src/auditlog_tests/tests.py
Fixes #108
Thanks to @andrewwatts for suggesting and researching the approach.
> Allow AuditlogHistoryField to block cascading deletes

- setup.py
This is useful so that websites like djangopackages.org can detect that this package supports Python 3.
https://djangopackages.org/packages/p/django-auditlog/
> Indicate Python 3 support in metadata

- .travis.yml
- setup.py
- src/auditlog_tests/router.py
- src/auditlog_tests/tests.py
- tox.ini
* Update test matrix to include all supported versions of Django and Python combinations
* Get tests to pass reliably
* Add support for Python 3.7
> Updated tests to support latest versions of Django and Python

- docs/source/usage.rst
dict.iteritems was removed from python 3. See [PEP 469](https://www.python.org/dev/peps/pep-0469/)
> change dict.iteritems to dict.items 

- auditlog/migrations/0008_action_index.py
- auditlog/models.py
For some applications the possibility to filter by the `action` field might be really interesting. However the lack of an index can lead to severe reduction of such queries.
The simplest solution: Let's a DB index on that field :)
> Add a DB index to `LogEntry`'s `action` field

- .github/workflows/test.yml
- docs/requirements.txt
- docs/source/installation.rst
- pyproject.toml
- setup.py
- tox.ini
Python 3.6 reaches end of life in December 2021.
This PR fixes CI too.
> build(python): remove python 3.6 support

- auditlog/diff.py
- auditlog/receivers.py
- auditlog_tests/tests.py
Solves #243 
This has been an irritating issue that I've been facing, the [issue](https://github.com/jazzband/django-auditlog/issues/243) seems to describe it quite well.
Please let me know if you have any comments :)
> Support Django's save method `update_fields` kwarg

- auditlog/migrations/0005_logentry_additional_data_verbose_name.py
- auditlog/migrations/0009_alter_logentry_additional_data.py
- auditlog/models.py
- auditlog_tests/test_settings.py
- auditlog_tests/tests.py
- setup.py
The `django-jsonfield` module is not maintained anymore and raises some errors with Django 4.0. So, as a recommendation in this package, and as Django 2.2 is still maintained, `django-jsonfield-backport` will do the job for the `JSONField` field.
Ref #43
Ref #334
PS: this PR is another try to solve what #271 is solving, but by keeping the `JSONField` field.
PPS: `django-jsonfield-backport` will be removed when Django 2.2 will be end of life (Django supports `JSONField` since 3.1).
> build: replace django-jsonfield with django-jsonfield-backport

- auditlog/apps.py
Developers who have set `DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'` in settings.py, and have django-auditlog installed, will be prompted to create a migration to migrate the Id field of LogeEntry to BigAutoField.
This PR sets the default_auto_field in the app config to match what is expressed in [0001_initial.py](https://github.com/jazzband/django-auditlog/blob/master/auditlog/migrations/0001_initial.py#L19), avoiding the nag for a potentially dangerous migration.
Related Issue: [#247](https://github.com/jazzband/django-auditlog/issues/247)
> Apply default_auto_field to app config.

- docs/requirements.txt
The `tox -e py38-docs` now fails with the following error:
```
Configuration error:
There is a programmable error in your configuration file:
Traceback (most recent call last):
File "jazzband/django-auditlog/.tox/py38-docs/lib/python3.8/site-packages/sphinx/config.py", line 329, in eval_config_file
exec(code, namespace)
File "jazzband/django-auditlog/docs/source/conf.py", line 26, in <module>
django.setup()
File "jazzband/django-auditlog/.tox/py38-docs/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
apps.populate(settings.INSTALLED_APPS)
File "work/jazzband/django-auditlog/.tox/py38-docs/lib/python3.8/site-packages/django/apps/registry.py", line 91, in populate
app_config = AppConfig.create(entry)
File "jazzband/django-auditlog/.tox/py38-docs/lib/python3.8/site-packages/ …
```
> Add django-jsonfield-backport to docs/requirements.txt to fix docs build.

- docs/source/conf.py
- pyproject.toml
The doc is build with python 3.8, which includes the `importlib` API to get the package version. Its use is recommanded by `setuptools-scm` for the doc.
> docs(conf): replace pkg_resources with importlib

- CHANGELOG.md
- auditlog/models.py
- auditlog_tests/tests.py
When you use replica database the django-auditlog try to write in the same database where object was read (replica). But this is a read only database and crash the application.
With this changes it saves always in the default database.
If you want to save in multiple databases or in a special one use `DATABASE_ROUTERS` to configure it.
To continue using multiple databases, you must configure it in your DATABASE ROUTERS.
> enable use of replica database

- CHANGELOG.md
- auditlog/diff.py
- auditlog_tests/models.py
- auditlog_tests/tests.py
- pyproject.toml
Fixes https://github.com/jazzband/django-auditlog/issues/354
> Skip stringify if json

- CHANGELOG.md
- auditlog/admin.py
- auditlog_tests/tests.py
Refresh https://github.com/jazzband/django-auditlog/pull/171
> Disable `add` button in admin ui

- pyproject.toml
This reverts commit 7bc39e6d9d51e7321bfca8793e21b8066d9859d3.
After this change the [readthedoc builds failed](https://readthedocs.org/projects/django-auditlog/builds/15827195/) because it uses python 3.7
> Revert "build: explicit the build system"

- CHANGELOG.md
- auditlog/apps.py
- auditlog/conf.py
- auditlog/registry.py
- auditlog_tests/test_settings.py
- auditlog_tests/tests.py
- docs/source/usage.rst
This PR makes it easy to register model in the django-auditlog.
`AUDITLOG_INCLUDE_ALL_MODELS` 
-> registers all models loaded from the django instance. 
```python
from django.apps import apps
apps.get_models()
```
e.g)
```python
AUDITLOG_INCLUDE_ALL_MODELS=True
```
`AUDITLOG_INCLUDE_TRACKING_MODELS` 
-> assign models to register.  this has the same behavior as `audit log.register()`
e.g)
```python
AUDITLOG_INCLUDE_TRACKING_MODELS = (
"<appname>.<model1>",
{
"model": "<appname>.<model1>",
"include_fields": ["field1", "field2"],
"exclude_fields": ["field3", "field4"],
"mapping_fields": {
"field1": "FIELD",
},
"mask_fields": ["field5", "field6"],
},
"<appname>.<model3>",
)
```
`AUDITLOG_EXCLUDE_TRACKING_MODELS` 
-> assign models to exclude. this option is executed when …
> Add register model using Django settings

- auditlog/models.py
- auditlog_tests/models.py
- auditlog_tests/tests.py
Add test for https://github.com/jazzband/django-auditlog/pull/317
Closes https://github.com/jazzband/django-auditlog/pull/273 and https://github.com/jazzband/django-auditlog/issues/293
Thanks, Michael Egan for sending the regression example by email.
> Return default value None if attribute choices doesn't exist

- auditlog_tests/test_settings.py
- auditlog_tests/tests.py
- tox.ini
There are three unrelated fixes and improvements in this pull request:
1. A typo in tox env list is fixed.
2. An expected warning is silenced in the tests.
3. Test configuration is adjusted to allow running `tox -p`.
The third item improves the total duration of tests (as measured by `time`) on the local machine drastically:
| command | sequential (no `-p` flag) | parallel (with `-p` flag) |
|----------|---------------------------|---------------------------|
| `tox` | 2:53.37 | 59.92 |
| `tox -r` | 4:55.11 | 1:37.75 |
Note: `tox -p` runs 8 envs in parallel on my machine by default. This number and thus the timings may be different depending on the configuration of your machine.
> Fix & improve running tests with tox

- CHANGELOG.md
- auditlog/mixins.py
- auditlog_tests/tests.py
> Display timestamps in server timezone

- CHANGELOG.md
- auditlog/middleware.py
- auditlog_tests/tests.py
Fixes https://github.com/jazzband/django-auditlog/issues/414 and https://github.com/jazzband/django-auditlog/issues/238
> Handle port in `remote_addr`

- CHANGELOG.md
- auditlog/mixins.py
- auditlog/models.py
- auditlog_tests/tests.py
Added verbose field name also using mapping name if defined (previously the mapping would not be used)
> Added verbose field name in admin

- auditlog/mixins.py
- auditlog_tests/tests.py
related #404 
already run the same code in the Django
ref: https://github.com/django/django/blob/3.2/django/contrib/admin/utils.py#L381-L429
```python
elif isinstance(field, models.DateTimeField):
return formats.localize(timezone.template_localtime(value))
```
> Remove unnecessary code in `created` method.

- CHANGELOG.md
- auditlog/diff.py
- auditlog/models.py
- auditlog_tests/tests.py
fixes https://github.com/jazzband/django-auditlog/issues/427
> Replace the `django.utils.timezone.utc` by `datetime.timezone.utc`

- CHANGELOG.md
- auditlog/admin.py
- auditlog_tests/tests.py
This is a follow-up fix after a real-world staff user deleted a few auditlog entries through the admin by mistake.
> Make log entries read-only in the admin

- CHANGELOG.md
- auditlog/middleware.py
- auditlog_tests/tests.py
> FIX: Parsing client IPv6 address when a proxy is involved

- CHANGELOG.md
- auditlog/models.py
- auditlog_tests/tests.py
`LogEntry.changes_str` raises an exception when viewing the new "accessed" AuditLog objects with no changes. This PR fixes `LogEntry.changes_dict()` so it always returns a dict, even if `json.loads() `returns `None`.
This PR fixes #471 which has the backtrace and more details :+1:
> Fix LogEntry.changes_dict() to return {} when json.loads() returns None

- auditlog/mixins.py
Using changes_dict to fix potential TypeError when changes are None in admin
Fixes #477
> Using changes_dict in admin list

- CHANGELOG.md
- auditlog/diff.py
- auditlog/receivers.py
- auditlog/signals.py
- auditlog_tests/tests.py
- docs/source/internals.rst
> Adding Custom Pre- and Post- Log Hooks

- CHANGELOG.md
- auditlog/diff.py
- auditlog/models.py
- auditlog_tests/models.py
- auditlog_tests/tests.py
~~I am going to write up an issue to relate to this PR in the next day or two. At the moment, I'm focused on getting this fix merged into our fork to resolve some bloating on our LogEntry table.~~ (Done, see attached issue)
Take a look and let me know what you think of this fix. I did look through the current issues and couldn't find anyone else complaining about this so maybe we've got some anti-patterns going on in our code. The issue is only happening in some of our more complex systems but I'm sure we're not that unique. I'll highlight the test case that shows the fix.
After letting this sit for an hour or two I realized this change will fix another more insidious bug. Currently, in cases where there are more than one object with the same string representation (e.g., two or more "John …
> Change diff to evaluate PKs for FK relationships

- auditlog/registry.py
- auditlog_tests/tests.py
Allow both list and tuple types for AUDITLOG_EXCLUDE_TRACKING_MODELS. Fixes #486
> Convert AUDITLOG_EXCLUDE_TRACKING_MODELS to tuple before concatenate

- CHANGELOG.md
- auditlog/diff.py
- auditlog_tests/models.py
- auditlog_tests/tests.py
Resolve #476 
My doubt is related to the [`sort_keys=True`](https://github.com/jazzband/django-auditlog/compare/master...CleitonDeLima:fix/476?expand=1#diff-575428ad5f7c4dfa79028063532473346bd6e1fb20894b2aa60053fad4e96cdfR78) of the dumps, I believe it is worth keeping for comparison reasons.
> Fix repr of a json field in field changes

- auditlog/registry.py
- auditlog_tests/tests.py
Includes a test to trigger the issue. Fixes #491
> raise AuditLogRegistrationError on invalid app in settings

- CHANGELOG.md
- auditlog/context.py
- auditlog/middleware.py
- auditlog_tests/tests.py
> Always call set_actor

- CHANGELOG.md
- auditlog/admin.py
- auditlog_tests/tests.py
As described in #493, this change inadvertently breaks deletion of auditlogged objects.
> Revert #449 "Disallow changing or deleting log entries"

- tox.ini
Django main branch is going to be prepared for version 5.0.
As [Django 5.0 requires Python >= 3.10](https://docs.djangoproject.com/en/dev/faq/install/#what-are-django-s-prerequisites), [the CI fails on django main and Python < 3.10](https://github.com/jazzband/django-auditlog/actions/runs/3952856514/jobs/6775443889)
> Run django main tests on Python >= 3.10

- CHANGELOG.md
- auditlog/conf.py
- auditlog/registry.py
- auditlog_tests/tests.py
- docs/source/usage.rst
My first stab at solving #467.
Adds the ability to list field names in ```AUDITLOG_EXCLUDE_TRACKING_MODELS``` that will be excluded from logging.
If a field in ```AUDITLOG_EXCLUDE_TRACKING_MODELS``` is the only field changed, nothing will be logged.
> Add ability to globally exclude fields by name on all models

- auditlog/models.py
fixes https://github.com/jazzband/django-auditlog/issues/502
> Add null=True to ci field

- CHANGELOG.md
- auditlog/mixins.py
- auditlog_tests/tests.py
Continue to https://github.com/jazzband/django-auditlog/pull/487
Thanks @nbensa for providing the test case
> Fix a bug in audit log admin page when `USE_TZ=False`

- .github/workflows/release.yml
- .github/workflows/test.yml
See these announcements:
- https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
- https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> Fix GitHub actions deprecations

- CHANGELOG.md
- auditlog/diff.py
- auditlog_tests/tests.py
In Django you can save changes to a FK field on a model using the ID field name (attname) in addition to the regular FK field name with:
model.related_model_id = 42
model.save(update_fields=["related_model_id'])
or:
model.related_model = related_model
model.save(update_fields=["related_model_id'])
as opposed to the more common:
model.related_model = related_model
model.save(update_fields=["related_model'])
This change ensures those model changes are logged properly.
> Audit changes to FK fields when saved using *_id naming.

- CHANGELOG.md
- auditlog/mixins.py
- auditlog_tests/tests.py
Sometimes, for example, when using a custom db router in microservices, there may not be direct access to the application / model. In such cases, we need te get at least field name.
> fixed getting field's verbose_name

- CHANGELOG.md
- auditlog/models.py
- auditlog_tests/tests.py
Closes https://github.com/jazzband/django-auditlog/issues/526
> Fix a bug in `serialized_data` with F expressions

- CHANGELOG.md
- auditlog/registry.py
- auditlog_tests/models.py
- auditlog_tests/tests.py
closes #315
closes #548 
feat: collect all models including auto created ones and excluding non-managed ones
feat: automatically register m2m fields for models when opting to auto register models
> Improve auto model registration

- CHANGELOG.md
- auditlog/models.py
- auditlog_tests/models.py
Based on the discussion in #493 and my comment at https://github.com/jazzband/django-auditlog/issues/493#issuecomment-1383913950, we should not delete audit log entries together with the tracked object by default.
> Set history delete_related to False by default

- CHANGELOG.md
- auditlog/admin.py
- auditlog_tests/tests.py
Resolves #493.
This pull request allows cascade deletion of log entries, but still disallows direct deletion through the admin.
> Allow cascade deletion of auditlog entries

- auditlog/receivers.py
We need to send audit log to logstash (this can apply to any external database/API), so we need the old model object to extract the changes.
> Pass instance_old to post_log.send

- CHANGELOG.md
- auditlog/receivers.py
- auditlog/signals.py
> fix: only fire the post_log signal when the log is created or when there is an error

- CHANGELOG.md
- auditlog/models.py
- auditlog/receivers.py
This pull request addresses two issues:
1. Even if a pk value is reused, we should not delete log entries for old deleted object. Old object's lifetime is easily identifiable by a pair of matching created & deleted log entries.
2. (why I started to look into this in the first place) `log_create` spends 22% of its run time calling `delete()` method in a test run of a medium-sized data loading job on my machine (7% of the total run time of the job).
I assume this is technically a breaking change so I'd like it included in 3.0.0 release too.
Notice the change in the `log_update` handler. Before my changes, every object creation was producing two log entries: `updated` log entry, then `created` log entry; and while creating this second log entry, auditlog was deleting the first one, so it was …
> Stop deleting log entries in log_create

- CHANGELOG.md
- auditlog/cid.py
It doesn't make sense to set it if we're not going to use it again.
> fix: don't set the correlation_id if the `AUDITLOG_CID_GETTER` is `None`

- auditlog/migrations/0015_alter_logentry_changes.py
closes #570 
my bad.
I don't know how this happened. The good thing is that verbose_name doesn't alter the db, so we don't need to create a migration for people already on v3.
> fix: change verbose_name in changes_text migration

- .readthedocs.yaml
Fixes https://github.com/jazzband/help/issues/345.
`pip install .` during the build to fix:
```pytb
Running Sphinx v7.2.6
Traceback (most recent call last):
File "/home/docs/checkouts/readthedocs.org/user_builds/django-auditlog/envs/latest/lib/python3.11/site-packages/sphinx/config.py", line 358, in eval_config_file
exec(code, namespace)  # NoQA: S102
^^^^^^^^^^^^^^^^^^^^^
File "/home/docs/checkouts/readthedocs.org/user_builds/django-auditlog/checkouts/latest/docs/source/conf.py", line 13, in <module>
from auditlog import __version__
ModuleNotFoundError: No module named 'auditlog'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/home/docs/checkouts/readthedocs.org/user_builds/django-auditlog/envs/latest/lib/python3.11/site-packa …
```
> Fix Read The Docs build

- .github/workflows/test.yml
- CHANGELOG.md
- setup.py
- tox.ini
I followed the pattern set by the previous 3.11 MR: #447 
The tox envlist change might be debatable, but my understanding is that Python 3.12 will only be supported on 4.2 and above.
As my colleague mentioned in #570, we've just started using v3 of this package, so happy to chip in with small things like this. I thought it might want adding for 3.0. We know that we shouldn't be using v3 yet, but the risk level is fine for what we're doing.
Thanks for your efforts!
> Confirm Python 3.12 support

- CHANGELOG.md
- auditlog/receivers.py
- auditlog/signals.py
- auditlog_tests/tests.py
If any receiver returns False, no logging will be made. This can be useful if logging should be conditionally enabled / disabled
Closes #589 possibly #586
> Conditionally disable / enable logging

- CHANGELOG.md
- auditlog/models.py
- auditlog_tests/models.py
- auditlog_tests/tests.py
> Handle `ObjectDoesNotExist` in evaluation of `object_repr`

- auditlog/receivers.py
- auditlog/signals.py
- auditlog_tests/tests.py
Thank you for maintaining this great project! While working on a specific use case where I wanted to further process audit messages, I stumbled across the fact that the `post_log` signal which has been introduced in v3 somehow does not contain the actual instance of the `LogEntry` that has been created and saved.
This was rather confusing to me and makes it impossible to implement my use case, which also requires access to fields like `cid`, `remote_addr`, `timestamp` or `actor` - for the latter I even found an open issue #576 on this repository, where a user was also missing the possibility to access the actor of a `LogEntry`.
While all kinds of fields could be added to the signal, I hereby propose to simply pass the actual `LogEntry` instance as part of the signal when available, which …
> Include `LogEntry` instance in `post_log` signal

- auditlog/models.py
- auditlog_tests/tests.py
As django-auditlog v3 now stores the actual PKs for foreign models instead of their string representation, I switched my application from `changes_dict` to `changes_display_dict` so that the actual string-representation of foreign models is being shown again. While this worked in my local environment, it broke while trying out this change against a previously used testing database, specifically by raising a `KeyError`.
As it turns out, if a model has been previously registered with django-auditlog and made any entries, followed by then being no longer registered (e.g. if the model has been deprecated or further logging is no longer desired), any calls to `changes_display_dict` will fail. The reason behind this is that the method attempts to lookup the model within the registry, without …
> Avoid exception in `changes_display_dict` when model is missing

- CHANGELOG.md
- auditlog/conf.py
- auditlog/middleware.py
- auditlog_tests/tests.py
- docs/source/usage.rst
Hello,
I've created this Pull Request in response to the user's request regarding the possibility to disable logging of the remote IP address in django-auditlog's audit logs (#524). This feature is desirable in the context of personal data protection, especially in compliance with the General Data Protection Regulation (GDPR).
In this Pull Request, I've added a new configuration, AUDITLOG_DISABLE_REMOTE_ADDR, which allows disabling the logging of the remote IP address. When this configuration is enabled, the remote IP address will no longer be recorded in the audit logs.
I've had to deal with this problem myself and I think it's important to address it for reasons of data confidentiality, which is why I've done this.
> Disable logging remote IP address

- auditlog/models.py
- auditlog_tests/models.py
- auditlog_tests/tests.py
If a model's primary key is another model, the current implementation of `LogEntryManager._get_pk_value` will needlessly pull in the entire object only to extract its primary key and discard it. This change gets the primary key directly from the first object.
The `attname` field isn't particularly well documented in Django, but it is briefly mentioned [here](https://docs.djangoproject.com/en/5.0/ref/models/fields/#django.db.models.Field.pre_save).
On the base `Field` class, it is the same as `name`:
https://github.com/django/django/blob/adae619426b6f50046b3daaa744db52989c9d6db/django/db/models/fields/__init__.py#L973-L974
Whereas for `ForeignKey`, it is `{name}_id`:
https://github.com/django/django/blob/adae619426b6f50046b3daaa744db52989c9d6db/django/db/models/fields/related.py#L1117-L1118 …
> Use `attname` to get pk value

- auditlog/management/commands/auditlogmigratejson.py
- auditlog_tests/test_two_step_json_migration.py
The [upgrade documentation](https://django-auditlog.readthedocs.io/en/latest/upgrade.html) recommends a multi-stage upgrade, during which some records might have a `changes` field that is no longer empty. This case is handled in the Django query but not in the Postgres one.
Additionally, if there are many records and the upgrade fails, we are returned to the initial state, which is not ideal.
This change should take care of these problems :crossed_fingers:
> Sync django query and postgres query

- auditlog_tests/test_two_step_json_migration.py
In some cases the tests break when the migration messages are output with colors in the terminal
> Added --no-color args in test migration

- .gitignore
- CHANGELOG.md
- auditlog/context.py
- auditlog/middleware.py
- auditlog/migrations/0016_logentry_remote_port.py
- auditlog/models.py
- auditlog_tests/tests.py
Resolve #668 
If there is another header to get the port I can include it too.
> Added remote port

- CHANGELOG.md
- auditlog/management/commands/auditlogflush.py
- auditlog_tests/test_commands.py
Fixes #680 
Passing `--truncate` to flush command executes a truncate SQL statement, instead of deleting log records.
> feat: Add truncate option to flush command

- auditlog/admin.py
Really nothing beyond the title
> Add date_hierarchy on timestamp to admin view

- CHANGELOG.md
- auditlog/models.py
- auditlog/receivers.py
- auditlog_tests/models.py
- auditlog_tests/tests.py
When using custom managers, I stumbled over unexpected behavior of the `log_update` signal. The signal directly uses the `objects` manager. From https://docs.djangoproject.com/en/5.1/topics/db/managers/#default-managers:
> If you’re writing some code that must handle an unknown model, for example, in a third-party app that implements a generic view, use this manager (or [_base_manager](https://docs.djangoproject.com/en/5.1/topics/db/managers/#django.db.models.Model._base_manager)) rather than assuming the model has an objects manager.
This is the result of some simple grepping, so it might not be complete.
> Use recommended manager to query related models

- CHANGELOG.md
- auditlog/receivers.py
- auditlog_tests/tests.py
Hi, thank you for `auditlog`.
This pull request fixes bug number #664. It is naive implementation but it seems that it works as expected. Please let me know what you think so I can adjust the patch accordingly.
> Fix IntegrityError when cloning objects with pk=None (#664)

- CHANGELOG.md
I did a quick check and I believe the listed changes don't include any breaking changes. I opted for v3.1.0. Please let me know if a different version number is better
Closes #713
> Prepare release 3.1.0

- .github/workflows/release.yml
- CHANGELOG.md
> CI: Add required pkginfo to release workflow

- .github/workflows/release.yml
- CHANGELOG.md
Pins setuptools to 75.6.0 and twine to 6.0.1 which hopefully fixes release problem according to comment here https://github.com/pypi/warehouse/issues/15611#issuecomment-2793628089
Not a huge fan of pinning dependencies but not sure if we have a different option right now. These pins should be removed down the line when it hopefully again works with latest version of setuptools and twine
Should fix https://github.com/jazzband/django-auditlog/issues/713
> Pin libraries to fix release

- CHANGELOG.md
- auditlog/conf.py
- auditlog/diff.py
- auditlog/receivers.py
- auditlog/registry.py
- auditlog_tests/test_settings.py
- auditlog_tests/test_use_json_for_changes.py
- docs/source/usage.rst
This is a PR that implements issue #675, basically, storing the correct JSON type that corresponds to the Python type (`None` -> null, `1 -> 1', not `"1"`).
It's driven by a setting, `AUDITLOG_ STORE_JSON_CHANGES `, as recommended by @hramezani
From #675:
> The values in the changes object stored in the database ju
> st get turned into strings, such that all type information is lost.
> Here is what the changes column looks like in the database:
> 
```{"is_cool": ["False", "True"], "age": ["None", "42"]}```
> Instead, I would expect the following:
> 
```
> >>> log_entry.changes
> {'is_cool': [False, True], 'age': [None, 42]}
> >>> type(log_entry.changes['age'][0])
> <class 'NoneType'>
> >>> type(log_entry.changes['age'][1])
> <class 'int'>
```
> and the following JSON in the DB:
> 
```
> …
```
> new setting: STORE_JSON_CHANGES that intelligently store JSON

- auditlog_tests/tests.py
Debian has moved legacy timezone names such as America/Buenos_Aires into
the tzdata-legacy package, which is not installed by default. The
canonical name for this timezone is America/Argentina/Buenos_Aires,
which remains in the standard tzdata package.
Update the test to use the canonical name to ensure compatibility with
default Debian installations.
> Use canonical timezone name for Buenos Aires

- CHANGELOG.md
- auditlog/mixins.py
- auditlog/render.py
- auditlog/templates/auditlog/entry_detail.html
- auditlog/templates/auditlog/object_history.html
- auditlog/templates/auditlog/pagination.html
- auditlog/templatetags/auditlog_tags.py
- auditlog_tests/test_render.py
- auditlog_tests/test_view.py
- docs/source/usage.rst
Add Admin integration feature to audit log history view for specific objects 
---
Closes #742
> Add audit log history view to Django Admin

- .github/actions/setup-python-deps/action.yml
- .github/workflows/test.yml
- auditlog/management/commands/auditlogflush.py
- auditlog_tests/docker-compose.yml
- auditlog_tests/docker/db/init-mysql.sh
- auditlog_tests/test_app/models.py
- auditlog_tests/test_commands.py
- auditlog_tests/test_postgresql.py
- auditlog_tests/test_settings.py
- auditlog_tests/test_two_step_json_migration.py
- auditlog_tests/tests.py
- docs/requirements.txt
- runtests.sh
- tox.ini
> Extend CI and local test coverage to MySQL and SQLite
